<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.2 on linux)" generated="20200513 22:05:52.304" rpa="false">
<suite id="s1" name="Repeatertest" source="/home/f00dog/Documents/Projects/Python/POCs/POC_UsingTaurusAndRF/repeatertest.robot">
<test id="s1-t1" name="Testing how to repeat tests">
<kw name="User can search for flights">
<msg timestamp="20200513 22:05:52.365" level="FAIL">No keyword with name 'User can search for flights' found.</msg>
<status status="FAIL" starttime="20200513 22:05:52.365" endtime="20200513 22:05:52.366"></status>
</kw>
<status status="FAIL" starttime="20200513 22:05:52.363" endtime="20200513 22:05:52.366" critical="yes">No keyword with name 'User can search for flights' found.</status>
</test>
<status status="FAIL" starttime="20200513 22:05:52.307" endtime="20200513 22:05:52.367"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Repeatertest">Repeatertest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200513 22:05:52.362" level="ERROR">Error in file '/home/f00dog/Documents/Projects/Python/POCs/POC_UsingTaurusAndRF/blazetest.robot' on line 4: Setting 'Suite Teardown' is not allowed in resource file.</msg>
<msg timestamp="20200513 22:05:52.362" level="ERROR">Error in file '/home/f00dog/Documents/Projects/Python/POCs/POC_UsingTaurusAndRF/repeatertest.robot' on line 2: Error in file '/home/f00dog/Documents/Projects/Python/POCs/POC_UsingTaurusAndRF/blazetest.robot' on line 10: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
